remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Course Notes of Peter Staab
description: This is where Symbolic Computation class notes are found.
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
